"""Refresh homepage statistics and featured projects.

Statistics come from the YTJobs profile. Featured Projects come from the
already-classified long-form portfolio generated by split_portfolio.py. This
keeps the homepage and portfolio on the same newest-first source of truth.

Writes two files the website reads on page load:
    assets/stats.json     -> "Audience Reached" + "Videos Delivered" numbers
    assets/projects.json  -> the 6 newest classified long-form videos

If this script fails, the old JSON (or the hardcoded HTML fallback) stays put.
"""
import datetime
import json
import os
import re
import sys
import urllib.request

PROFILE_URL = "https://ytjobs.co/talent/profile/48926"
BASE = os.path.join(os.path.dirname(__file__), "..")
STATS_OUT = os.path.join(BASE, "assets", "stats.json")
PROJECTS_OUT = os.path.join(BASE, "assets", "projects.json")
LONGFORM_IN = os.path.join(BASE, "portfolio_longform.json")
PROJECT_COUNT = 6

UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"


def fetch_html():
    req = urllib.request.Request(PROFILE_URL, headers={"User-Agent": UA})
    try:
        return urllib.request.urlopen(req, timeout=30).read().decode("utf-8", "ignore")
    except Exception as e:
        print(f"Fetch failed: {e}", file=sys.stderr)
        raise SystemExit(1)


def write_stats(html, today):
    m = re.search(r'"youtubeVideos":\{"statistics":\{"views":(\d+),"counts":(\d+)', html)
    if not m:
        print("Stats not found — YTJobs layout may have changed.", file=sys.stderr)
        raise SystemExit(1)
    views, videos = int(m.group(1)), int(m.group(2))
    data = {
        "audience_reached": f"{views // 1_000_000}M+",
        "videos_delivered": f"{videos}+",
        "views_raw": views,
        "videos_raw": videos,
        "updated": today,
        "source": PROFILE_URL,
    }
    with open(STATS_OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"stats.json   -> {data['audience_reached']} audience, "
          f"{data['videos_delivered']} videos")


def featured_projects(videos):
    """Convert newest-first long-form entries to the homepage card schema."""
    out = []
    for v in videos[:PROJECT_COUNT]:
        url = v.get("youtube_url", "")
        ytid = v.get("youtube_id", "")
        out.append({
            "title": v.get("title", "").strip(),
            "url": url,
            "views": v.get("views_formatted", ""),
            "thumbnail": (f"https://i.ytimg.com/vi/{ytid}/hqdefault.jpg"
                          if ytid else v.get("thumbnail", "")),
        })
    return out


def write_projects(today):
    try:
        with open(LONGFORM_IN, encoding="utf-8-sig") as f:
            videos = json.load(f).get("videos", [])
    except (OSError, json.JSONDecodeError) as e:
        print(f"Could not read classified portfolio: {e}", file=sys.stderr)
        raise SystemExit(1)

    out = featured_projects(videos)
    if not out:
        print("Classified portfolio has no long-form videos.", file=sys.stderr)
        raise SystemExit(1)

    data = {"updated": today, "source": PROFILE_URL, "videos": out}
    with open(PROJECTS_OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"projects.json -> {len(out)} most-recent videos")


def main():
    today = datetime.date.today().isoformat()
    # Keep Featured Projects independent from the statistics request. If the
    # profile page is temporarily unavailable, the newly classified work is
    # still written for the homepage before this script reports the failure.
    write_projects(today)
    html = fetch_html()
    write_stats(html, today)


if __name__ == "__main__":
    main()
