"""Refresh homepage statistics and featured projects.

Statistics come from portfolio_videos.json, written by the same YTJobs API
refresh that supplies the portfolio. Featured Projects come from the
already-classified long-form portfolio generated by split_portfolio.py. This
keeps the homepage and portfolio on one source of truth and avoids scraping
YTJobs page markup.

Writes two files the website reads on page load:
    assets/stats.json     -> "Audience Reached" + "Videos Delivered" numbers
    assets/projects.json  -> the 6 newest classified long-form videos

If this script fails, the old JSON (or the hardcoded HTML fallback) stays put.
"""
import datetime
import json
import os
import sys

SOURCE_URL = "https://app.ytjobs.co/api/talents/48926/videos"
BASE = os.path.join(os.path.dirname(__file__), "..")
STATS_OUT = os.path.join(BASE, "assets", "stats.json")
PROJECTS_OUT = os.path.join(BASE, "assets", "projects.json")
PORTFOLIO_IN = os.path.join(BASE, "portfolio_videos.json")
LONGFORM_IN = os.path.join(BASE, "portfolio_longform.json")
PROJECT_COUNT = 6


def stats_payload(portfolio_stats, previous, today):
    """Build homepage stats, retaining last known raw values if needed."""
    views = portfolio_stats.get("total_views_raw")
    videos = portfolio_stats.get("total_videos")
    if not isinstance(views, int):
        views = previous.get("views_raw")
    if not isinstance(videos, int):
        videos = previous.get("videos_raw")
    if not isinstance(views, int) or not isinstance(videos, int):
        raise ValueError("Portfolio statistics are incomplete")
    return {
        "audience_reached": f"{views // 1_000_000}M+",
        "videos_delivered": f"{videos}+",
        "views_raw": views,
        "videos_raw": videos,
        "updated": portfolio_stats.get("updated") or previous.get("updated") or today,
        "source": SOURCE_URL,
    }


def write_stats(today):
    try:
        with open(PORTFOLIO_IN, encoding="utf-8-sig") as f:
            portfolio_stats = json.load(f).get("portfolio_stats", {})
    except (OSError, json.JSONDecodeError) as exc:
        print(f"Could not read portfolio statistics: {exc}", file=sys.stderr)
        raise SystemExit(1)
    try:
        with open(STATS_OUT, encoding="utf-8-sig") as f:
            previous = json.load(f)
    except (OSError, json.JSONDecodeError):
        previous = {}
    try:
        data = stats_payload(portfolio_stats, previous, today)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        raise SystemExit(1)
    with open(STATS_OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"stats.json   -> {data['audience_reached']} audience, "
          f"{data['videos_delivered']} videos")


def featured_projects(videos):
    """Convert newest-first long-form entries to the homepage card schema."""
    out = []
    for v in videos[:PROJECT_COUNT]:
        url = v.get("youtube_url", "")
        ytid = v.get("youtube_id", "")
        out.append({
            "title": v.get("title", "").strip(),
            "url": url,
            "views": v.get("views_formatted", ""),
            "thumbnail": (f"https://i.ytimg.com/vi/{ytid}/hqdefault.jpg"
                          if ytid else v.get("thumbnail", "")),
        })
    return out


def write_projects(today):
    try:
        with open(LONGFORM_IN, encoding="utf-8-sig") as f:
            videos = json.load(f).get("videos", [])
    except (OSError, json.JSONDecodeError) as e:
        print(f"Could not read classified portfolio: {e}", file=sys.stderr)
        raise SystemExit(1)

    out = featured_projects(videos)
    if not out:
        print("Classified portfolio has no long-form videos.", file=sys.stderr)
        raise SystemExit(1)

    data = {"updated": today, "source": SOURCE_URL, "videos": out}
    with open(PROJECTS_OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"projects.json -> {len(out)} most-recent videos")


def main():
    today = datetime.date.today().isoformat()
    write_projects(today)
    write_stats(today)


if __name__ == "__main__":
    main()
